/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: components["schemas"]["UserResponse"];
        ErrorResponse: components["schemas"]["Unauthorized"];
        UserResponse: {
            id?: number;
            name?: string;
        };
        Unauthorized: {
            error?: string;
        };
    };
    responses: {
        /** @description Login successful */
        LoginSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    token?: string;
                    user?: components["schemas"]["UserResponse"];
                };
            };
        };
        /** @description Invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Unauthorized"];
            };
        };
    };
    parameters: never;
    requestBodies: {
        LoginRequest: {
            content: {
                "application/json": components["requestBodies"]["LoginRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LoginRequest"];
        responses: {
            200: components["responses"]["LoginSuccess"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
